<?php
include_once('DBConn.class.php');

class STKPush extends DBConn{

    function initSTKPush($url,$Password,$token,$curl,$BusinessShortCode,$Timestamp,$TransactionType,$Amount,
                         $PartyA,$PartyB,$PhoneNumber,$CallBackURL,$AccountReference,$TransactionDesc){

        curl_setopt($curl, CURLOPT_URL, $url);
        curl_setopt($curl, CURLOPT_HTTPHEADER, array('Content-Type:application/json', 'Authorization:Bearer '.$token)); //setting custom header

        $curl_post_data = array(
            //Fill in the request parameters with valid values
            'BusinessShortCode' => $BusinessShortCode,//The organization shortcode used to receive the transaction.
            'Password' => $Password,//This is generated by base64 encoding BusinessShortcode, Passkey and Timestamp.
            'Timestamp' => $Timestamp,//The timestamp of the transaction in the format yyyymmddhhiiss.
            'TransactionType' => $TransactionType,//The transaction type to be used for this request.
            'Amount' => $Amount,//The amount to be transacted.
            'PartyA' => $PartyA,//The MSISDN sending the funds.
            'PartyB' => $PartyB,//The organization shortcode receiving the funds
            'PhoneNumber' => $PhoneNumber,//The MSISDN sending the funds.
            'CallBackURL' => $CallBackURL,//The url to where logs from M-Pesa will be sent to.
            'AccountReference' => $AccountReference,//Used with M-Pesa PayBills.
            'TransactionDesc' => $TransactionDesc//A description of the transaction.
        );

        $data_string = json_encode($curl_post_data);

        curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);
        curl_setopt($curl, CURLOPT_POST, true);
        curl_setopt($curl, CURLOPT_POSTFIELDS, $data_string);

        $curl_response = curl_exec($curl);
        print_r($curl_response);
    }
}